### ISSUE TITLE
linode.errors.ApiError: 400: Invalid JSON; from null json

### ISSUE THREAD

**Issue by gummiboll** [linode/python-linode-api#100]
Hello!

Not really sure if this is a problem with the api-wrapper or the actual api itself since this error just started happening today and I haven't upgraded the wrapper since I last ran the same script successfully. Either way, when I use get_instances I get a stacktrace;

```
>>> c = linode.LinodeClient(supersecretkeygoeshere)
>>> linodes = c.linode.get_instances(linode.Linode.label == 'name of a linode')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/emil/code/jenkins-scripts/env/lib/python2.7/site-packages/linode/linode_client.py", line 31, in get_instances
    return self.client._get_and_filter(Linode, *filters)
  File "/Users/emil/code/jenkins-scripts/env/lib/python2.7/site-packages/linode/linode_client.py", line 656, in _get_and_filter
    return self._get_objects(obj_type.api_list(), obj_type, filters=parsed_filters)
  File "/Users/emil/code/jenkins-scripts/env/lib/python2.7/site-packages/linode/linode_client.py", line 487, in _get_objects
    response_json = self.get(endpoint, model=model, filters=filters)
  File "/Users/emil/code/jenkins-scripts/env/lib/python2.7/site-packages/linode/linode_client.py", line 503, in get
    return self._api_call(*args, method=requests.get, **kwargs)
  File "/Users/emil/code/jenkins-scripts/env/lib/python2.7/site-packages/linode/linode_client.py", line 477, in _api_call
    raise ApiError(error_msg, status=response.status_code, json=j)
linode.errors.ApiError: 400: Invalid JSON;
```

After digging down in linode_client.py it seems like the problem happens when the client sends empty json to the api:

```
def _api_call(self, endpoint, model=None, method=None, data=None, filters=None):
    ....
    body = json.dumps(data) # evaluates to null if data is omitted/None
    response = method(url, headers=headers, data=body)

```
I did a simple hack to get everything up and running again (check if data is None and if it is don't send the body through method() and that works but feels pretty hackish.

**Comment by Dorthu** [comment]
Thanks for reporting this, I'm looking into it now

**Comment by Dorthu** [comment]
This is fixed in version `4.1.8b1`.  A `pip install --upgrade linode-api` should get it up and running again.  Sorry for the inconvenience.

**Comment by angaunba** [comment]
Hi,

It worked but at the same broke down linode-cli.

```
Traceback (most recent call last):
  File "/usr/local/bin/linode-cli", line 7, in <module>
    from linodecli.cli import main
  File "/usr/local/lib/python3.6/site-packages/linodecli/cli.py", line 12, in <module>
    package_version = pkg_resources.require("linode-cli")[0].version,
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 984, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 875, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (linode-api 4.1.8b1 (/usr/local/lib/python3.6/site-packages), Requirement.parse('linode-api==4.1.7b0'), {'linode-cli'})
```

**Comment by rmcintosh** [comment]
@angaunba If you run `pip install --upgrade linode-cli`, you should get an updated version of the CLI app, which we've just pushed out

**Comment by angaunba** [comment]
Wow, that was fast. 👍
Thanks! :)
