### ISSUE TITLE
No attribute 'api_list'

### ISSUE THREAD

**Issue by jo-tez** [linode/python-linode-api#14]
Constantly getting the following error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/private/var/mobile/Containers/Shared/AppGroup/CA9211C1-E493-4FEA-A4C6-C8E83E68A908/Pythonista3/Documents/code/LinodeAPI/linode/linode_client.py", line 22, in get_instances
    return self.client._get_and_filter(Linode, *filters)
  File "/private/var/mobile/Containers/Shared/AppGroup/CA9211C1-E493-4FEA-A4C6-C8E83E68A908/Pythonista3/Documents/code/LinodeAPI/linode/linode_client.py", line 304, in _get_and_filter
    return self._get_objects(obj_type.api_list(), obj_type, filters=parsed_filters)
AttributeError: type object 'Linode' has no attribute 'api_list'
```

**Comment by Dorthu** [comment]
I could not reproduce this.  How did you get it to happen?  What python version are you using?

**Comment by jo-tez** [comment]
I'm using Python 3.5. 
I'm just recreating my app with a new "vanilla" setup for the linode-api environment, to try to isolate the issue and will report back with more info
